export const USER_RECOVERY_EMAIL_REQUEST = 'USER_RECOVERY_EMAIL_REQUEST';
export const USER_RECOVERY_EMAIL_SUCCESS = 'USER_RECOVERY_EMAIL_SUCCESS';
export const USER_RECOVERY_EMAIL_FAIL = 'USER_RECOVERY_EMAIL_FAIL';
export const USER_RECOVERY_EMAIL_RESET = 'USER_RECOVERY_EMAIL_RESET';

export const USER_RECOVERY_EMAIL_AND_OTP_REQUEST = 'USER_RECOVERY_EMAIL_AND_OTP_REQUEST';
export const USER_RECOVERY_EMAIL_AND_OTP_SUCCESS = 'USER_RECOVERY_EMAIL_AND_OTP_SUCCESS';
export const USER_RECOVERY_EMAIL_AND_OTP_FAIL = 'USER_RECOVERY_EMAIL_AND_OTP_FAIL';
export const USER_RECOVERY_EMAIL_AND_OTP_RESET = 'USER_RECOVERY_EMAIL_AND_OTP_RESET';

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';
export const USER_RESET_PASSWORD_RESET = 'USER_RESET_PASSWORD_RESET';
