export const USER_RECOVERY_EMAIL_REQUEST = 'USER_RECOVERY_EMAIL_REQUEST';
export const USER_RECOVERY_EMAIL_SUCCESS = 'USER_RECOVERY_EMAIL_SUCCESS';
export const USER_RECOVERY_EMAIL_FAIL = 'USER_RECOVERY_EMAIL_FAIL';
