export const USER_RECOVERY_EMAIL_REQUEST = 'USER_RECOVERY_EMAIL_REQUEST';
export const USER_RECOVERY_EMAIL_SUCCESS = 'USER_RECOVERY_EMAIL_SUCCESS';
export const USER_RECOVERY_EMAIL_FAIL = 'USER_RECOVERY_EMAIL_FAIL';

export const USER_RECOVERY_EMAIL_AND_OTP_REQUEST = 'USER_RECOVERY_EMAIL_AND_OTP_REQUEST';
export const USER_RECOVERY_EMAIL_AND_OTP_SUCCESS = 'USER_RECOVERY_EMAIL_AND_OTP_SUCCESS';
export const USER_RECOVERY_EMAIL_AND_OTP_FAIL = 'USER_RECOVERY_EMAIL_AND_OTP_FAIL';
